// Created by iWeb 3.0.4 local-build-20170221

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-5,5,10,146),url:'Publications_files/stroke_8.png'},{rect:new IWRect(-5,-5,10,10),url:'Publications_files/stroke_9.png'},{rect:new IWRect(5,-5,243,10),url:'Publications_files/stroke_10.png'},{rect:new IWRect(248,-5,11,10),url:'Publications_files/stroke_11.png'},{rect:new IWRect(248,5,11,146),url:'Publications_files/stroke_12.png'},{rect:new IWRect(248,151,11,10),url:'Publications_files/stroke_13.png'},{rect:new IWRect(5,151,243,10),url:'Publications_files/stroke_14.png'},{rect:new IWRect(-5,151,10,10),url:'Publications_files/stroke_15.png'}],new IWSize(254,156)),stroke_0:new IWStrokeParts([{rect:new IWRect(-5,5,10,275),url:'Publications_files/stroke.png'},{rect:new IWRect(-5,-5,10,10),url:'Publications_files/stroke_1.png'},{rect:new IWRect(5,-5,397,10),url:'Publications_files/stroke_2.png'},{rect:new IWRect(402,-5,11,10),url:'Publications_files/stroke_3.png'},{rect:new IWRect(402,5,11,275),url:'Publications_files/stroke_4.png'},{rect:new IWRect(402,280,11,10),url:'Publications_files/stroke_5.png'},{rect:new IWRect(5,280,397,10),url:'Publications_files/stroke_6.png'},{rect:new IWRect(-5,280,10,10),url:'Publications_files/stroke_7.png'}],new IWSize(407,285)),stroke_2:new IWStrokeParts([{rect:new IWRect(-5,5,10,318),url:'Publications_files/stroke_16.png'},{rect:new IWRect(-5,-5,10,10),url:'Publications_files/stroke_17.png'},{rect:new IWRect(5,-5,245,10),url:'Publications_files/stroke_18.png'},{rect:new IWRect(250,-5,10,10),url:'Publications_files/stroke_19.png'},{rect:new IWRect(250,5,10,318),url:'Publications_files/stroke_20.png'},{rect:new IWRect(250,323,10,11),url:'Publications_files/stroke_21.png'},{rect:new IWRect(5,323,245,11),url:'Publications_files/stroke_22.png'},{rect:new IWRect(-5,323,10,11),url:'Publications_files/stroke_23.png'}],new IWSize(255,328))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Publications_files/PublicationsMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');Widget.onload();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
